/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

/**
 *
 * @author Aluno
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_funcionario = new javax.swing.JTable();
        bt_pesquisarFunc = new javax.swing.JButton();
        tf_funcionario = new javax.swing.JTextField();
        lb_produto = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        bt_NovoFunc = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        bt_ExcluirFunc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_SalvarFunc = new javax.swing.JButton();
        bt_EditarFunc = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Chico Almeida", "16/12/97", "111.222.333-21", "Caixa", "12345"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Data de Nascimento", "CPF", "Função", "Matrícula"
            }
        ));
        jScrollPane1.setViewportView(tb_funcionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 473, 140));

        bt_pesquisarFunc.setText("Pesquisar");
        getContentPane().add(bt_pesquisarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 13, -1, -1));
        getContentPane().add(tf_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 14, 357, -1));

        lb_produto.setText("Nome:");
        getContentPane().add(lb_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 129, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 129, -1));

        jLabel1.setText("Data de Nascimento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel6.setText("Função:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 129, -1));

        bt_NovoFunc.setText("Novo");
        getContentPane().add(bt_NovoFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 63, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 129, -1));

        bt_ExcluirFunc.setText("Excluir");
        bt_ExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExcluirFuncActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ExcluirFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, -1, -1));

        bt_SalvarFunc.setText("Salvar");
        getContentPane().add(bt_SalvarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 231, -1, -1));

        bt_EditarFunc.setText("Editar");
        getContentPane().add(bt_EditarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 260, 63, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void bt_ExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExcluirFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ExcluirFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_EditarFunc;
    private javax.swing.JButton bt_ExcluirFunc;
    private javax.swing.JButton bt_NovoFunc;
    private javax.swing.JButton bt_SalvarFunc;
    private javax.swing.JButton bt_pesquisarFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lb_produto;
    private javax.swing.JTable tb_funcionario;
    private javax.swing.JTextField tf_funcionario;
    // End of variables declaration//GEN-END:variables
}
